In [15]:
import copy
import os 
import sys

import numpy as np
import open3d as o3d

In [33]:
pc = o3d.io.read_point_cloud("dst.ply")
print(pc)

sigma = 0.005
SEED = 0
print(pc.points)
np.random.seed(SEED)
noise = np.random.normal(0, sigma, np.asarray(pc.points).shape)
print(noise)
print(noise.shape)


PointCloud with 198835 points.
std::vector<Eigen::Vector3d> with 198835 elements.
Use numpy.asarray() to access data.
[[ 8.82026173e-03  2.00078604e-03  4.89368992e-03]
 [ 1.12044660e-02  9.33778995e-03 -4.88638940e-03]
 [ 4.75044209e-03 -7.56786041e-04 -5.16094259e-04]
 ...
 [-5.05037959e-03 -6.88794606e-03 -9.49988538e-03]
 [-5.02440760e-03 -2.68379635e-04 -4.32011874e-03]
 [-3.47708674e-07 -4.56205985e-03 -3.45473604e-03]]
(198835, 3)


In [34]:

pc_with_noise = copy.deepcopy(pc)
print(np.asarray(pc.points))
print(noise)
points_with_noise = np.asarray(pc.points) + noise
pc_with_noise.points = o3d.utility.Vector3dVector(points_with_noise)

o3d.io.write_point_cloud(f"dst_noise_{sigma}.ply", pc_with_noise)

[[0.27405298 1.02095513 1.12868408]
 [0.29389196 1.01755603 1.1406841 ]
 [0.30689903 1.01520229 1.14901173]
 ...
 [0.49888183 2.42827751 1.63517043]
 [0.49521603 2.43012446 1.63321714]
 [0.49414874 2.42849813 1.63447699]]
[[ 8.82026173e-03  2.00078604e-03  4.89368992e-03]
 [ 1.12044660e-02  9.33778995e-03 -4.88638940e-03]
 [ 4.75044209e-03 -7.56786041e-04 -5.16094259e-04]
 ...
 [-5.05037959e-03 -6.88794606e-03 -9.49988538e-03]
 [-5.02440760e-03 -2.68379635e-04 -4.32011874e-03]
 [-3.47708674e-07 -4.56205985e-03 -3.45473604e-03]]


True

In [12]:
pc_noise = o3d.geometry.PointCloud()
pc_noise.points = o3d.utility.Vector3dVector(noise)
o3d.io.write_point_cloud("noise.ply", pc_noise)

True